### ISSUE TITLE
Money Format requires Linux or additional packages for windows 

### ISSUE THREAD

**Issue by lukepolo** [lukepolo/laracart#2]
Need to find a new way to format the money

**Comment by dsfser** [comment]
could you describe the problem?

**Comment by lukepolo** [comment]
According to the PHP docs money_format is available for windows: 

http://php.net/manual/en/function.money-format.php#refsect1-function.money-format-notes

LaraCart relies heavily on the money_format function , Id like it to be cross platform so no one has to worry about it.

**Comment by dsfser** [comment]
ahh i see!

i have found this sollution for this problem:

http://www.php.net/manual/en/function.money-format.php#89060

you could implement that function for the platforms that do not bear it.

**Comment by dsfser** [comment]
i am not using windows as my server so i will not be facing this problem

**Comment by lukepolo** [comment]
Correct, enjoy !

**Comment by dsfser** [comment]
Was using "gloudemans/shoppingcart": "~1.3"

but yours is way better ;)

**Comment by dsfser** [comment]
Thanks!

**Comment by didadan** [comment]
Why do you want this anyway? In my opinion your cart solution should handle all cart related functions and the amounts, totals ... should be handled the same way (i.e. all numbers in cents). Then there should be some other separate and external logic handeling the currency and formatting (Some countries write a comma instead of a point and vice versa, thousand separators etc.). You could add this as a layer before everything is returned. I wouldn't use the money format but instead give a few configuration options and use php dealing with all the formatting.

**Comment by lukepolo** [comment]
1. I probably should give an option to just give it out in cents.
2. I already give the functionality of locale and international support

Money format supports these : 
http://lh.2xlibre.net/locales/

**Comment by lukepolo** [comment]
#100

**Comment by umbertix** [comment]
What about: http://php.net/manual/en/numberformatter.formatcurrency.php ?

**Comment by lukepolo** [comment]
Only problem is it would require them to install the intl PHP package. Which is annoying to an end user. 

http://php.net/manual/en/book.intl.php

**Comment by umbertix** [comment]
what about: https://github.com/commerceguys/intl ?

**Comment by lukepolo** [comment]
That could work . Will look into it

**Comment by lukepolo** [comment]
Version 2 will address this issue
