### ISSUE TITLE
Does cart have option to get the Total price without tax?

### ISSUE THREAD

**Issue by dsfser** [lukepolo/laracart#76]
as of now the plugin asumes that the product price is without tax and adds the default tax to the item. 

any way to turn this into total = total with tax?

so:

product: 100 euro
tax percent: 21%
product ex tax: 79 euro
taxes: 21 euro
cart total: 100 euro

**Comment by lukepolo** [comment]
product: 100 euro (is this with or without tax)


to get the total price without tax is easy enough you want to use LaraCart::subTotal()

**Comment by dsfser** [comment]
product: 100 euro is with tax

**Comment by lukepolo** [comment]
You have 2 questions in this then .

"Does cart have option to get the Total price without tax?"  - yes , LaraCart::subTotal()

"Can we show the product with tax" - yes but you must do two calls : $item->price(false) + $item->tax()

But be careful when you do this. The reasoning behind why they are separate is because if you have a discount on the cart that must be applied before we apply the tax on the item.

**Comment by lukepolo** [comment]
Will this solve both of your questions ?

**Comment by dsfser** [comment]
yes, thank you!
