### ISSUE TITLE
Update event fire to laravel 5.2

### ISSUE THREAD

**Issue by Wit3** [lukepolo/laracart#94]
Laravel 5.2 fire event 

`Event::fire(new PodcastWasPurchased($podcast));`

in previous versions of laravel, the events listeners were defined in this way

```
protected $listen = [
    'event.name' => [
        'EventListener',
    ],
];
```

Now in 5.2 :

```
protected $listen = [
    'App\Events\UserSignup' => [
        'App\Handlers\Events\EmailTheAccountCreatorConfirmationLink',
        'App\Handlers\Events\NotifyTheAdminThatNewAccountHasBeenCreated',
    ],
];

```

 Please update the event firing

**Comment by lukepolo** [comment]
You should be able to listen to them the old way. The only difference is one has a class name instead. I could upgrade mine to fire 

$this->events->fire(LaraCart\Events\NewCart::class);

which would look more like LaraCart\Events\NewCart

I will have to make a major change aka 1.2 since it would have breaking changes for users already listening to the events the old way. 


Iill mark this as a 1.2 change.

**Comment by sahilsharma011** [comment]
Hello
I am working on this
I'll be submitting a PR in a couple of days

**Comment by lukepolo** [comment]
@sahilsharma011 your amazing
